// Copyright (c) 2016 Drew Crawford.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.



// This file is automatically generated by Caroline and should not be edited by hand.
import CarolineCore
let allTests: [CarolineTest] = [
    BadDecrypt(),
    ChaCha20(),
    Crypto(),
    CryptoBox(),
    CryptoBoxFromBytes(),
    CryptoBoxKey(),
    CryptoBoxOpen(),
    DecryptTest(),
    DeriveKey(),
    EncryptTest(),
    GenerateKey(),
    GenericHash(),
    HumanReadable(),
    Integer192BitTests(),
    KeyLoadSave(),
    KeyTest(),
    MemCmpTest(),
    OverwriteKey(),
    PublicKeyLoadSave(),
    TestBadVerify(),
    TestSign(),
    TestVerify(),
    ZeroImport()
]
let engine = CarolineCoreEngine()
if !engine.testAll(allTests) {
    fatalError("Caroline tests failed")
}
